### PR TITLE
This is how the folders should be

### PR DESCRIPTION
**Pull request by arcbtc**
So people can easily install using manifest.

Not in this pr, but I forked and changed the org in the manifest here so I can install and test https://raw.githubusercontent.com/arcbtc/DeviceTimer/orgchange/manifest.json
To be installed like:
image

### CODE REVIEW

**Comment by arcbtc** [comment]
Cool idea adding donation link

**Comment by dni** [comment]
this is already done on main

**Comment by dni** [comment]
and i also think we should push that to upstream https://github.com/pieterjm/DeviceTimer

**Comment by DoktorShift** [comment]
Its done. Ich PRd the changes to https://github.com/pieterjm/DeviceTimer

**Comment by dni** [comment]
close it then :)

**Pull request closed without merging**
